adding .figure-caption styles
az-digital/arizona-bootstrap pull request #330
Opened 2021-07-04 16:20 UTC by smayden

2021-07-07 16:56 UTC, mmunro-ltrr approved these changes
Looked similar to the review site on a local build, & passed local linting checks: just wondering where the specific color came from (#eef1f1) since we don't seem to use it elsewhere.

2021-07-07 17:37 UTC, trackleft requested changes

2021-07-07 17:37 UTC, trackleft commented on scss/_custom-styles.scss
> +  border-bottom: 1px solid #eef1f1;
I think we should use a color var here?

2021-07-07 18:00 UTC, trackleft commented on scss/_custom-styles.scss
> +  border-bottom: 1px solid #eef1f1;
```suggestion
  border-bottom: 1px solid $gray-200;
```

2021-07-07 18:10 UTC, trackleft commented on scss/_custom-styles.scss
> +  border-bottom: 1px solid #eef1f1;
Alternate color suggestion.
```suggestion
  border-bottom: 1px solid $hr-border-color;
```

2021-07-07 20:56 UTC, smayden commented
Per suggestions by Chris and Martin, this had be altered to use an existing brand color already set in bootstrap (gray200).

Should be ready for final review

2021-07-07 21:03 UTC, mmunro-ltrr approved these changes
Re-checked locally: prefer the non-arbitrary color anyway.

2021-07-09 17:35 UTC, trackleft approved these changes

2021-07-09 17:35 UTC, tadean approved these changes

2021-07-09 17:36 UTC, merged