Closes 1823: Remove uppercase text decoration from main nav
az-digital/arizona-bootstrap pull request #535
Opened 2022-08-19 16:10 UTC by cpoff

Removed uppercase text transform from three nav scss files in AZ Bootstrap.

_navbar.scss
_nav.scss
_navbar-offcanvas.scss

Changed `uppercase` to `none` on all three.

2022-08-19 17:25 UTC, camikazegreen commented
Link to review site: https://review.digital.arizona.edu/arizona-bootstrap/issue/1823-remove-uppercase-nav/docs/2.0/components/navbar/ 

Original docs for comparison: https://digital.arizona.edu/arizona-bootstrap/docs/2.0/components/navbar/

2022-08-19 17:25 UTC, camikazegreen approved these changes
This changes looks good to me.

2022-08-19 17:33 UTC, mmunro-ltrr approved these changes
Checked on the review site.

2022-08-19 17:43 UTC, danahertzberg requested changes
Need to run by leadership for approval before merging

2022-08-19 17:45 UTC, danahertzberg commented
Add documentation around good navbar use to Bootstrap

2022-08-19 17:53 UTC, danahertzberg commented
Change in inspector:
- Non-dropdown menu items

```
.navbar-nav .nav-link {
    font-weight: 600;
    text-transform: none;
    background-color: inherit;
    border: none;
}
```
- Dropdown menu items
```
.navbar-offcanvas .nav-item-parent .nav-link {
    text-transform: none;
}
```

2022-08-31 16:45 UTC, danahertzberg approved these changes

2022-08-31 17:50 UTC, trackleft commented on scss/_nav.scss
>        background-color: $nav-tabs-link-active-bg;
Should we not just remove the text-transform?

2022-08-31 17:51 UTC, merged

2022-08-31 17:51 UTC, trackleft commented on scss/_nav.scss
>        background-color: $nav-tabs-link-active-bg;
NVM none is better, since this will add an underline if not there, and adding a text-transform utility class will still work.